services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    networks: 
      - medco 
    environment:
      MYSQL_DATABASE: "medco_main"
      MYSQL_ROOT_PASSWORD: "databaserootpwd"
      MYSQL_USER: "databaseuser"
      MYSQL_PASSWORD: "databasepwd"
    restart: always
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ../backend
    container_name: backend
    restart: always
    networks:
      - medco
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://databaseuser:databasepwd@mysql:3306/medco_main"
      SHADOW_DATABASE_URL: "mysql://root:databaserootpwd@mysql:3306/medco_main"
      DB_HOST: "mysql"
      DB_NAME: "medco_main"
      DB_PASS: "databasepwd"
      DB_USER: "databaseuser"
      DB_PORT: "3306"
      PORT: "3007"
      FRONT_END_URL: "http://localhost:3008"
      DEV_MODE: true
    ports:
      - "3007:3007"
    volumes:
      - ../backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "3008:3008"
    depends_on:
      - backend
    environment:
      VITE_BACKEND_URL: "http://localhost:3007"
    volumes:
      - ../frontend:/usr/src/app
      - /usr/src/app/node_modules

networks:
  medco:
    name: medco